### ISSUE TITLE
where is test.json

### ISSUE THREAD

**Issue by 2212168851** [cooelf/SG-Net#4]
Traceback (most recent call last):
   File "run_race.py", line 1104, in <module>
     main()
   File "run_race.py", line 1014, in main
     is_training=True)
   File "run_race.py", line 185, in read_race_examples
     article, question, ct1, ct2, ct3, ct4, y, q_id = rea_race(input_file)
   File "run_race.py", line 140, in rea_race
     with open(path, 'r', encoding='utf_8') as f:
 FileNotFoundError: [Errno 2] No such file or directory: 'test.json'

please update 'test.json'

**Comment by cooelf** [comment]
It was generated by the annotation and converting script. The convert script has been uploaded.
